/**
 * What each note smells like, in one plain line, for "How it smells" on the
 * product page (Notes you can touch). Keyed by the note's name in lower case;
 * a note without a line still shows, with its name and when it arrives.
 * Drafts for the owner and perfumer to adjust.
 */
export const noteLines: Record<string, string> = {
  // Citrus
  bergamot: "Bright, slightly bitter citrus with a floral edge.",
  "marine bergamot": "Bergamot with a salty, sea-air lift.",
  lemon: "Sharp, sunny and clean.",
  orange: "Juicy and sweet, like peel pressed between the fingers.",
  mandarin: "Soft, sweet citrus, gentler than orange.",
  grapefruit: "Tart and sparkling, with a bitter zest.",
  citron: "Thick-skinned citrus: green, sharp and aromatic.",
  citrus: "A bright mix of fresh citrus peel.",
  petitgrain: "Green and woody, from the leaves and twigs of the orange tree.",
  // Fruit
  apple: "Crisp, cold and green.",
  "wild apple": "Crisp and green, a bite of cold apple.",
  pear: "Juicy, watery and lightly sweet.",
  peach: "Soft, velvety and ripe.",
  apricot: "Sun-warm stone fruit, sweet and a little tangy.",
  mango: "Ripe, tropical and honeyed.",
  pineapple: "Sharp and juicy, more zest than sugar.",
  coconut: "Creamy and milky, like sun lotion on warm skin.",
  "coconut milk": "Soft, creamy sweetness.",
  melon: "Cool, watery and fresh.",
  fig: "Green, milky fig with a woody edge.",
  strawberry: "Ripe and jammy.",
  raspberry: "Bright, tart berry.",
  blackcurrant: "Tangy dark berry with a green, leafy bite.",
  "green rhubarb": "Tart and green, with a pink, juicy snap.",
  "luminous fruit accord": "A bright, juicy blend of fresh fruit.",
  // Gourmand
  "white rum": "A warm, boozy sweetness.",
  "mojito accord": "Lime, mint and a splash of rum.",
  pistachio: "Nutty, creamy and a little salty.",
  almond: "Soft marzipan sweetness.",
  "salted caramel": "Burnt sugar with a pinch of salt.",
  "brown sugar": "Warm, molasses-dark sweetness.",
  // Spice
  "black pepper": "A dry spark that wakes the opening up.",
  pepper: "Dry and peppery, a crackle of heat.",
  "pink pepper": "Rosy and fizzy, a soft prickle.",
  "sichuan pepper": "Citrusy, tingling pepper.",
  ginger: "Fresh and zesty, with a warm bite.",
  cardamom: "Cool spice, like cardamom in coffee.",
  coriander: "Spicy and citrusy, a little green.",
  nutmeg: "Warm, sweet spice.",
  saffron: "Leathery, golden and slightly bitter.",
  "aromatic spices": "A warm handful of mixed spices.",
  // Herbs and green
  mint: "Cool and bright, straight from the leaf.",
  rosemary: "Resinous and herbal, like a crushed sprig.",
  "clary sage": "Herbal and musky, with a hint of tea.",
  lavender: "Clean, herbal and calming.",
  juniper: "Crisp, piney and gin-like.",
  cypress: "Green, resinous and a little bitter.",
  maté: "Green tea and dry hay.",
  "black tea": "Dry and smoky tea leaves.",
  "smoky black tea": "Smoked tea leaves, dry and dark.",
  "green notes": "Freshly cut stems and leaves.",
  "fig leaf": "Green and milky, like a torn fig leaf.",
  geranium: "Green leaf with a faint rose edge.",
  // Flowers
  neroli: "Orange blossom, bright and clean, with a little honey.",
  "orange blossom": "Sweet, honeyed white flowers.",
  "apple blossom": "Light, fresh and faintly fruity petals.",
  jasmine: "Rich, sweet white flowers.",
  "jasmine sambac": "Lush, fruity jasmine.",
  tuberose: "Creamy, heady white flowers.",
  gardenia: "Creamy, green-edged white petals.",
  magnolia: "Fresh, lemony white flower.",
  rose: "Velvety, classic rose.",
  violet: "Powdery, sweet and a little green.",
  iris: "Cool and powdery, like soft suede.",
  orris: "Iris root: powdery, like the inside of a compact.",
  marigold: "Green and bitter-sweet petals.",
  waterlily: "Watery, airy and clean.",
  heliotrope: "Almond-sweet and powdery.",
  "vanilla orchid": "The vanilla flower: soft, sweet and creamy.",
  "white flowers": "A soft bouquet of white petals.",
  "white florals": "A soft bouquet of white petals.",
  "aquatic florals": "Petals in cool water.",
  ambrette: "Musky seeds, soft and a little pear-like.",
  // Woods, resins and the base
  cedar: "Dry, clean wood, like a pencil just sharpened.",
  cedarwood: "Dry, clean wood, like a pencil just sharpened.",
  sandalwood: "Creamy, smooth wood.",
  birch: "Smoky, leathery wood.",
  driftwood: "Weathered, salty wood.",
  woods: "Warm, dry wood.",
  "dry woods": "Dry, clean wood.",
  "light woods": "Soft, pale wood.",
  "ambery woods": "Warm wood with a resinous glow.",
  "woody amber": "Warm wood with a resinous glow.",
  amberwood: "Dry, warm and radiant wood.",
  amber: "Warm resin that holds the scent on skin.",
  ambergris: "Salty, warm and skin-like.",
  ambroxan: "Clean, mineral warmth that clings to skin.",
  labdanum: "Dark, sticky resin, warm and leathery.",
  olibanum: "Incense: clean, peppery smoke.",
  incense: "Smoke with no fire behind it.",
  "fir resin": "Balsamic and piney.",
  patchouli: "Earthy and dark, deep in the drydown.",
  vetiver: "Smoky roots, earthy and cool.",
  oakmoss: "Damp forest floor, green and earthy.",
  tonka: "Almond and warm hay, the sweetness at the end.",
  vanilla: "Warm, sweet and creamy.",
  "vanilla pods": "Dark, almost boozy vanilla straight from the pod.",
  musk: "Soft, clean skin-scent.",
  "white musk": "Soft and clean, like warm cotton.",
  // Sea and air
  "sea salt": "Salt spray on skin.",
  salt: "A pinch of sea salt.",
  "sea breeze": "Fresh, open air off the water.",
  "marine notes": "The smell of open water.",
  "mineral accord": "Wet stone after a wave.",
};

/** The line for a note, if one is written. */
export const noteLine = (name: string): string | null => noteLines[name.toLowerCase()] ?? null;
