/**
 * Each scent's notes by tier, from its Shopify description, and where each
 * pictured note sits on its notes sculpture (public/images/products/<handle>-3),
 * as [x, y] in percent of the photo. A note without `at` is not in the photo.
 * Drives "How it smells" (NotesTouch). Mango Eclipse and Smoked Aura join once
 * their notes are known.
 */
export type NoteTier = "Top" | "Heart" | "Base";
export type MappedNote = { name: string; tier: NoteTier; at?: readonly [number, number] };

export const noteMaps: Record<string, MappedNote[]> = {
  "aqua-marine": [
    { name: "Orange", tier: "Top", at: [80, 61] },
    { name: "Mandarin", tier: "Top", at: [26, 35] },
    { name: "Bergamot", tier: "Top", at: [24, 67] },
    { name: "Ginger", tier: "Heart", at: [51, 31] },
    { name: "Ambergris", tier: "Base", at: [49, 17] },
  ],
  atlantis: [
    { name: "Sea salt", tier: "Top", at: [14, 77] },
    { name: "Mineral accord", tier: "Top" },
    { name: "Fig leaf", tier: "Heart", at: [14, 44] },
    { name: "Marine notes", tier: "Heart" },
    { name: "Woody amber", tier: "Base", at: [64, 25] },
    { name: "Driftwood", tier: "Base", at: [57, 12] },
  ],
  atomic: [
    { name: "Lemon", tier: "Top", at: [42, 22] },
    { name: "Black pepper", tier: "Top", at: [27, 54] },
    { name: "Lavender", tier: "Heart", at: [70, 28] },
    { name: "Olibanum", tier: "Heart", at: [16, 70] },
    { name: "Amber", tier: "Base", at: [78, 55] },
    { name: "Tonka", tier: "Base", at: [85, 73] },
  ],
  carbon: [
    { name: "Bergamot", tier: "Top", at: [21, 55] },
    { name: "Pepper", tier: "Top", at: [24, 74] },
    { name: "Sichuan pepper", tier: "Heart", at: [7, 71] },
    { name: "Lavender", tier: "Heart", at: [21, 34] },
    { name: "Geranium", tier: "Heart", at: [60, 27] },
    { name: "Ambroxan", tier: "Base" },
    { name: "Cedar", tier: "Base", at: [82, 50] },
    { name: "Labdanum", tier: "Base", at: [77, 68] },
  ],
  "caribbean-punch": [
    { name: "Mango", tier: "Top", at: [22, 42] },
    { name: "Pineapple", tier: "Top", at: [63, 17] },
    { name: "Coconut", tier: "Top", at: [84, 44] },
    { name: "White rum", tier: "Top" },
    { name: "Bergamot", tier: "Top", at: [28, 60] },
    { name: "Coconut milk", tier: "Heart", at: [79, 82] },
    { name: "White flowers", tier: "Heart" },
    { name: "Marine notes", tier: "Heart" },
    { name: "Musk", tier: "Base" },
    { name: "Sandalwood", tier: "Base", at: [7, 72] },
    { name: "Amber", tier: "Base", at: [22, 74] },
    { name: "Vetiver", tier: "Base", at: [86, 73] },
  ],
  cipher: [
    { name: "Pineapple", tier: "Top", at: [53, 17] },
    { name: "Bergamot", tier: "Top", at: [27, 38] },
    { name: "Grapefruit", tier: "Top", at: [75, 46] },
    { name: "Jasmine", tier: "Heart", at: [45, 36] },
    { name: "Cedar", tier: "Heart", at: [22, 57] },
    { name: "Oakmoss", tier: "Base", at: [17, 73] },
    { name: "Dry woods", tier: "Base", at: [84, 73] },
  ],
  citron: [
    { name: "Bergamot", tier: "Top", at: [48, 18] },
    { name: "Lemon", tier: "Top", at: [23, 48] },
    { name: "Neroli", tier: "Top", at: [74, 19] },
    { name: "Marigold", tier: "Top", at: [90, 54] },
    { name: "Violet", tier: "Heart", at: [16, 62] },
    { name: "Jasmine", tier: "Heart", at: [73, 44] },
    { name: "Vetiver", tier: "Base", at: [7, 72] },
    { name: "Cedar", tier: "Base", at: [94, 70] },
    { name: "Musk", tier: "Base" },
    { name: "Amber", tier: "Base", at: [78, 72] },
  ],
  destiny: [
    { name: "Orange blossom", tier: "Top", at: [33, 35] },
    { name: "Bergamot", tier: "Top", at: [55, 21] },
    { name: "Tuberose", tier: "Heart", at: [84, 42] },
    { name: "Jasmine", tier: "Heart" },
    { name: "Vanilla", tier: "Base", at: [70, 50] },
    { name: "White musk", tier: "Base", at: [17, 51] },
    { name: "Cedar", tier: "Base", at: [69, 68] },
  ],
  divina: [
    { name: "Bergamot", tier: "Top", at: [55, 17] },
    { name: "Pink pepper", tier: "Top", at: [28, 34] },
    { name: "Gardenia", tier: "Heart", at: [54, 34] },
    { name: "Orris", tier: "Heart", at: [31, 47] },
    { name: "Jasmine", tier: "Heart", at: [72, 57] },
    { name: "White musk", tier: "Base", at: [21, 63] },
    { name: "Sandalwood", tier: "Base", at: [20, 77] },
    { name: "Amber", tier: "Base", at: [77, 73] },
  ],
  eden: [
    { name: "Green notes", tier: "Top" },
    { name: "Mint", tier: "Top", at: [71, 48] },
    { name: "Ginger", tier: "Top", at: [40, 22] },
    { name: "Coconut", tier: "Heart", at: [80, 31] },
    { name: "Fig", tier: "Heart", at: [88, 63] },
    { name: "Salt", tier: "Heart", at: [73, 72] },
    { name: "Tonka", tier: "Base", at: [12, 73] },
    { name: "Sandalwood", tier: "Base", at: [20, 60] },
  ],
  element: [
    { name: "Saffron", tier: "Top", at: [48, 13] },
    { name: "Jasmine", tier: "Top", at: [23, 25] },
    { name: "Amberwood", tier: "Heart" },
    { name: "Ambergris", tier: "Heart", at: [15, 52] },
    { name: "Fir resin", tier: "Base", at: [25, 41] },
    { name: "Cedar", tier: "Base", at: [82, 68] },
  ],
  "enzo-1898": [
    { name: "Citrus", tier: "Top" },
    { name: "Mandarin", tier: "Top", at: [43, 12] },
    { name: "Grapefruit", tier: "Top", at: [60, 25] },
    { name: "Cedarwood", tier: "Heart", at: [20, 32] },
    { name: "White musk", tier: "Base", at: [6, 60] },
    { name: "Amber", tier: "Base", at: [18, 68] },
    { name: "Patchouli", tier: "Base", at: [83, 52] },
    { name: "Sandalwood", tier: "Base", at: [78, 70] },
  ],
  fiji: [
    { name: "Citrus", tier: "Top", at: [83, 53] },
    { name: "Aquatic florals", tier: "Heart", at: [25, 38] },
    { name: "Musk", tier: "Base", at: [65, 27] },
    { name: "Ambergris", tier: "Base", at: [39, 19] },
  ],
  "forbidden-apple": [
    { name: "Apple blossom", tier: "Top", at: [59, 16] },
    { name: "Marine bergamot", tier: "Top", at: [63, 38] },
    { name: "Green rhubarb", tier: "Heart", at: [18, 54] },
    { name: "Mojito accord", tier: "Heart", at: [88, 54] },
    { name: "Sandalwood", tier: "Base", at: [17, 69] },
    { name: "Driftwood", tier: "Base", at: [71, 70] },
  ],
  "golden-hour": [
    { name: "Melon", tier: "Top", at: [46, 22] },
    { name: "Bergamot", tier: "Top", at: [27, 39] },
    { name: "Lemon", tier: "Top", at: [29, 54] },
    { name: "Sea salt", tier: "Top", at: [74, 58] },
    { name: "Iris", tier: "Heart", at: [80, 42] },
    { name: "Waterlily", tier: "Heart", at: [12, 57] },
    { name: "Musk", tier: "Base" },
    { name: "Ambergris", tier: "Base", at: [84, 71] },
    { name: "Woods", tier: "Base" },
  ],
  harmony: [
    { name: "Bergamot", tier: "Top", at: [43, 16] },
    { name: "Magnolia", tier: "Top", at: [54, 35] },
    { name: "Orange blossom", tier: "Heart", at: [30, 42] },
    { name: "Ambrette", tier: "Heart", at: [18, 78] },
    { name: "White musk", tier: "Base", at: [70, 58] },
  ],
  hera: [
    { name: "Strawberry", tier: "Top", at: [25, 44] },
    { name: "Raspberry", tier: "Top", at: [60, 23] },
    { name: "Blackcurrant", tier: "Top", at: [29, 31] },
    { name: "Jasmine", tier: "Heart", at: [52, 17] },
    { name: "Violet", tier: "Heart", at: [75, 52] },
    { name: "Musk", tier: "Base" },
    { name: "Amber", tier: "Base", at: [68, 42] },
    { name: "Dry woods", tier: "Base" },
  ],
  "hundred-whispers": [
    { name: "Peach", tier: "Top", at: [46, 22] },
    { name: "Coconut", tier: "Top", at: [22, 39] },
    { name: "Tuberose", tier: "Heart", at: [88, 40] },
    { name: "Jasmine sambac", tier: "Heart", at: [76, 75] },
    { name: "Orris", tier: "Heart", at: [14, 55] },
    { name: "Vanilla", tier: "Base", at: [20, 25] },
    { name: "Sandalwood", tier: "Base", at: [14, 75] },
    { name: "Musk", tier: "Base" },
  ],
  icon: [
    { name: "Pineapple", tier: "Top", at: [12, 71] },
    { name: "Bergamot", tier: "Top", at: [32, 37] },
    { name: "Blackcurrant", tier: "Top", at: [26, 57] },
    { name: "Apple", tier: "Top", at: [13, 55] },
    { name: "Birch", tier: "Heart" },
    { name: "Patchouli", tier: "Heart" },
    { name: "Rose", tier: "Heart", at: [78, 34] },
    { name: "Oakmoss", tier: "Base", at: [84, 68] },
    { name: "Musk", tier: "Base", at: [50, 17] },
    { name: "Ambergris", tier: "Base", at: [76, 57] },
    { name: "Vanilla", tier: "Base", at: [24, 18] },
  ],
  linen: [
    { name: "Neroli", tier: "Top", at: [37, 16.5] },
    { name: "Black pepper", tier: "Top", at: [52, 27] },
    { name: "Iris", tier: "Heart", at: [70, 28] },
    { name: "Geranium", tier: "Heart", at: [17, 47] },
    { name: "Maté", tier: "Heart", at: [70, 46] },
    { name: "Amber", tier: "Base", at: [81, 61] },
    { name: "Cedar", tier: "Base", at: [17, 72] },
    { name: "Patchouli", tier: "Base", at: [85, 76] },
  ],
  mercury: [
    { name: "Grapefruit", tier: "Top", at: [77, 47] },
    { name: "Luminous fruit accord", tier: "Heart" },
    { name: "Amberwood", tier: "Base", at: [24, 70] },
    { name: "Musk", tier: "Base", at: [45, 20] },
  ],
  mystique: [
    { name: "Pistachio", tier: "Top", at: [24, 71] },
    { name: "Almond", tier: "Top", at: [17, 52] },
    { name: "Heliotrope", tier: "Heart", at: [31, 22] },
    { name: "Jasmine", tier: "Heart", at: [82, 40] },
    { name: "Salted caramel", tier: "Base", at: [28, 38] },
    { name: "Vanilla", tier: "Base", at: [44, 18.5] },
    { name: "Sandalwood", tier: "Base", at: [73, 20] },
  ],
  "neroli-code": [
    { name: "Neroli", tier: "Top", at: [82, 60] },
    { name: "Petitgrain", tier: "Top", at: [62, 87] },
    { name: "Smoky black tea", tier: "Heart" },
    { name: "White musk", tier: "Base" },
  ],
  oasis: [
    { name: "Citron", tier: "Top", at: [55, 20] },
    { name: "Bergamot", tier: "Top", at: [28, 40] },
    { name: "Orange", tier: "Top", at: [81, 45] },
    { name: "Black tea", tier: "Heart", at: [14, 71] },
    { name: "Ginger", tier: "Heart", at: [88, 64] },
    { name: "Ambroxan", tier: "Base" },
  ],
  poseidon: [
    { name: "Sea breeze", tier: "Top" },
    { name: "Citrus", tier: "Top", at: [46, 17] },
    { name: "White florals", tier: "Heart", at: [21, 19] },
    { name: "Sea salt", tier: "Heart", at: [58, 32] },
    { name: "Ambergris", tier: "Base", at: [73, 46] },
    { name: "Light woods", tier: "Base", at: [17, 68] },
    { name: "Musk", tier: "Base", at: [82, 71] },
  ],
  "raw-seduction": [
    { name: "Wild apple", tier: "Top", at: [46, 11] },
    { name: "Bergamot", tier: "Top", at: [65, 38] },
    { name: "Cardamom", tier: "Heart", at: [84, 52] },
    { name: "Cypress", tier: "Heart", at: [18, 42] },
    { name: "Cedar", tier: "Base", at: [13, 70] },
    { name: "Vetiver", tier: "Base", at: [76, 63] },
    { name: "Tonka", tier: "Base", at: [82, 78] },
  ],
  sapphire: [
    { name: "Pear", tier: "Top", at: [51, 23] },
    { name: "Ginger", tier: "Top", at: [25, 43] },
    { name: "Mint", tier: "Top", at: [76, 45] },
    { name: "Orange blossom", tier: "Heart", at: [21, 60] },
    { name: "Ambroxan", tier: "Base" },
    { name: "White musk", tier: "Base", at: [84, 71] },
  ],
  "secret-no-7": [
    { name: "Pear", tier: "Top", at: [53, 20] },
    { name: "Bergamot", tier: "Top", at: [17, 69.5] },
    { name: "Vanilla orchid", tier: "Heart", at: [24, 45] },
    { name: "Vetiver", tier: "Base", at: [84, 31] },
    { name: "Ambroxan", tier: "Base" },
    { name: "Vanilla", tier: "Base", at: [17.5, 23.5] },
  ],
  "shadow-of-the-sea": [
    { name: "Marine notes", tier: "Top" },
    { name: "Bergamot", tier: "Top", at: [10, 65] },
    { name: "Rosemary", tier: "Heart", at: [24, 23.5] },
    { name: "Clary sage", tier: "Heart", at: [40, 16.5] },
    { name: "Geranium", tier: "Heart", at: [72, 20] },
    { name: "Patchouli", tier: "Base", at: [90, 69] },
    { name: "Incense", tier: "Base", at: [75.5, 65] },
    { name: "Ambery woods", tier: "Base" },
  ],
  "shore-club": [
    { name: "Lemon", tier: "Top", at: [48, 11] },
    { name: "Orange", tier: "Top", at: [30, 29] },
    { name: "Blackcurrant", tier: "Top", at: [62, 23] },
    { name: "Mint", tier: "Heart", at: [19, 38] },
    { name: "Coriander", tier: "Heart", at: [84, 32.5] },
    { name: "Apricot", tier: "Heart", at: [10, 52] },
    { name: "Ambrette", tier: "Base" },
    { name: "Musk", tier: "Base", at: [84, 60] },
  ],
  "tonic-club": [
    { name: "Juniper", tier: "Top", at: [28, 39] },
    { name: "Coriander", tier: "Top", at: [21, 59] },
    { name: "Nutmeg", tier: "Heart", at: [19.5, 72] },
    { name: "Aromatic spices", tier: "Heart" },
    { name: "Musk", tier: "Base", at: [84, 31] },
    { name: "Ambery woods", tier: "Base" },
    { name: "Vanilla", tier: "Base", at: [50, 19] },
  ],
  "vanilla-blanche": [
    { name: "Brown sugar", tier: "Top", at: [40, 22] },
    { name: "Jasmine", tier: "Top", at: [72.5, 31.5] },
    { name: "Vanilla orchid", tier: "Heart", at: [21, 64] },
    { name: "Tonka", tier: "Heart", at: [27, 78] },
    { name: "Amber", tier: "Base", at: [19, 41] },
    { name: "Musk", tier: "Base" },
    { name: "Patchouli", tier: "Base", at: [84, 67] },
  ],
  "vintage-vanilla": [
    { name: "Vanilla pods", tier: "Top", at: [40, 27] },
    { name: "Orris", tier: "Heart", at: [27, 37.5] },
    { name: "White musk", tier: "Heart", at: [74, 25] },
    { name: "Sandalwood", tier: "Base", at: [75, 60] },
    { name: "Tonka", tier: "Base", at: [84, 74] },
  ],
  wayne: [
    { name: "Bergamot", tier: "Top", at: [38.5, 39.5] },
    { name: "Pineapple", tier: "Top", at: [57, 30] },
    { name: "Pink pepper", tier: "Top", at: [54, 40.5] },
    { name: "Lavender", tier: "Heart", at: [77, 52] },
    { name: "Cedar", tier: "Heart", at: [28, 53] },
    { name: "Incense", tier: "Heart", at: [24, 77] },
    { name: "Ambroxan", tier: "Base" },
    { name: "Patchouli", tier: "Base", at: [77, 71] },
    { name: "Birch", tier: "Base" },
  ],
};
