/**
 * Each scent's notes by tier, from its Shopify description, and where each
 * pictured note sits on its notes sculpture (public/images/products/<handle>-3),
 * as [x, y] in percent of the photo. A note without `at` is not in the photo.
 * Drives "How it smells" (NotesTouch). Mango Eclipse and Smoked Aura join once
 * their notes are known.
 */
export type NoteTier = "Top" | "Heart" | "Base";
export type MappedNote = { name: string; tier: NoteTier; at?: readonly [number, number] };

export const noteMaps: Record<string, MappedNote[]> = {
  "aqua-marine": [
    { name: "Orange", tier: "Top" },
    { name: "Mandarin", tier: "Top" },
    { name: "Bergamot", tier: "Top" },
    { name: "Ginger", tier: "Heart" },
    { name: "Ambergris", tier: "Base" },
  ],
  atlantis: [
    { name: "Sea salt", tier: "Top" },
    { name: "Mineral accord", tier: "Top" },
    { name: "Fig leaf", tier: "Heart" },
    { name: "Marine notes", tier: "Heart" },
    { name: "Woody amber", tier: "Base" },
    { name: "Driftwood", tier: "Base" },
  ],
  atomic: [
    { name: "Lemon", tier: "Top" },
    { name: "Black pepper", tier: "Top" },
    { name: "Lavender", tier: "Heart" },
    { name: "Olibanum", tier: "Heart" },
    { name: "Amber", tier: "Base" },
    { name: "Tonka", tier: "Base" },
  ],
  carbon: [
    { name: "Bergamot", tier: "Top" },
    { name: "Pepper", tier: "Top" },
    { name: "Sichuan pepper", tier: "Heart" },
    { name: "Lavender", tier: "Heart" },
    { name: "Geranium", tier: "Heart" },
    { name: "Ambroxan", tier: "Base" },
    { name: "Cedar", tier: "Base" },
    { name: "Labdanum", tier: "Base" },
  ],
  "caribbean-punch": [
    { name: "Mango", tier: "Top" },
    { name: "Pineapple", tier: "Top" },
    { name: "Coconut", tier: "Top" },
    { name: "White rum", tier: "Top" },
    { name: "Bergamot", tier: "Top" },
    { name: "Coconut milk", tier: "Heart" },
    { name: "White flowers", tier: "Heart" },
    { name: "Marine notes", tier: "Heart" },
    { name: "Musk", tier: "Base" },
    { name: "Sandalwood", tier: "Base" },
    { name: "Amber", tier: "Base" },
    { name: "Vetiver", tier: "Base" },
  ],
  cipher: [
    { name: "Pineapple", tier: "Top" },
    { name: "Bergamot", tier: "Top" },
    { name: "Grapefruit", tier: "Top" },
    { name: "Jasmine", tier: "Heart" },
    { name: "Cedar", tier: "Heart" },
    { name: "Oakmoss", tier: "Base" },
    { name: "Dry woods", tier: "Base" },
  ],
  citron: [
    { name: "Bergamot", tier: "Top" },
    { name: "Lemon", tier: "Top" },
    { name: "Neroli", tier: "Top" },
    { name: "Marigold", tier: "Top" },
    { name: "Violet", tier: "Heart" },
    { name: "Jasmine", tier: "Heart" },
    { name: "Vetiver", tier: "Base" },
    { name: "Cedar", tier: "Base" },
    { name: "Musk", tier: "Base" },
    { name: "Amber", tier: "Base" },
  ],
  destiny: [
    { name: "Orange blossom", tier: "Top" },
    { name: "Bergamot", tier: "Top" },
    { name: "Tuberose", tier: "Heart" },
    { name: "Jasmine", tier: "Heart" },
    { name: "Vanilla", tier: "Base" },
    { name: "White musk", tier: "Base" },
    { name: "Cedar", tier: "Base" },
  ],
  divina: [
    { name: "Bergamot", tier: "Top" },
    { name: "Pink pepper", tier: "Top" },
    { name: "Gardenia", tier: "Heart" },
    { name: "Orris", tier: "Heart" },
    { name: "Jasmine", tier: "Heart" },
    { name: "White musk", tier: "Base" },
    { name: "Sandalwood", tier: "Base" },
    { name: "Amber", tier: "Base" },
  ],
  eden: [
    { name: "Green notes", tier: "Top" },
    { name: "Mint", tier: "Top" },
    { name: "Ginger", tier: "Top" },
    { name: "Coconut", tier: "Heart" },
    { name: "Fig", tier: "Heart" },
    { name: "Salt", tier: "Heart" },
    { name: "Tonka", tier: "Base" },
    { name: "Sandalwood", tier: "Base" },
  ],
  element: [
    { name: "Saffron", tier: "Top" },
    { name: "Jasmine", tier: "Top" },
    { name: "Amberwood", tier: "Heart" },
    { name: "Ambergris", tier: "Heart" },
    { name: "Fir resin", tier: "Base" },
    { name: "Cedar", tier: "Base" },
  ],
  "enzo-1898": [
    { name: "Citrus", tier: "Top" },
    { name: "Mandarin", tier: "Top" },
    { name: "Grapefruit", tier: "Top" },
    { name: "Cedarwood", tier: "Heart" },
    { name: "White musk", tier: "Base" },
    { name: "Amber", tier: "Base" },
    { name: "Patchouli", tier: "Base" },
    { name: "Sandalwood", tier: "Base" },
  ],
  fiji: [
    { name: "Citrus", tier: "Top" },
    { name: "Aquatic florals", tier: "Heart" },
    { name: "Musk", tier: "Base" },
    { name: "Ambergris", tier: "Base" },
  ],
  "forbidden-apple": [
    { name: "Apple blossom", tier: "Top" },
    { name: "Marine bergamot", tier: "Top" },
    { name: "Green rhubarb", tier: "Heart" },
    { name: "Mojito accord", tier: "Heart" },
    { name: "Sandalwood", tier: "Base" },
    { name: "Driftwood", tier: "Base" },
  ],
  "golden-hour": [
    { name: "Melon", tier: "Top" },
    { name: "Bergamot", tier: "Top" },
    { name: "Lemon", tier: "Top" },
    { name: "Sea salt", tier: "Top" },
    { name: "Iris", tier: "Heart" },
    { name: "Waterlily", tier: "Heart" },
    { name: "Musk", tier: "Base" },
    { name: "Ambergris", tier: "Base" },
    { name: "Woods", tier: "Base" },
  ],
  harmony: [
    { name: "Bergamot", tier: "Top" },
    { name: "Magnolia", tier: "Top" },
    { name: "Orange blossom", tier: "Heart" },
    { name: "Ambrette", tier: "Heart" },
    { name: "White musk", tier: "Base" },
  ],
  hera: [
    { name: "Strawberry", tier: "Top" },
    { name: "Raspberry", tier: "Top" },
    { name: "Blackcurrant", tier: "Top" },
    { name: "Jasmine", tier: "Heart" },
    { name: "Violet", tier: "Heart" },
    { name: "Musk", tier: "Base" },
    { name: "Amber", tier: "Base" },
    { name: "Dry woods", tier: "Base" },
  ],
  "hundred-whispers": [
    { name: "Peach", tier: "Top" },
    { name: "Coconut", tier: "Top" },
    { name: "Tuberose", tier: "Heart" },
    { name: "Jasmine sambac", tier: "Heart" },
    { name: "Orris", tier: "Heart" },
    { name: "Vanilla", tier: "Base" },
    { name: "Sandalwood", tier: "Base" },
    { name: "Musk", tier: "Base" },
  ],
  icon: [
    { name: "Pineapple", tier: "Top" },
    { name: "Bergamot", tier: "Top" },
    { name: "Blackcurrant", tier: "Top" },
    { name: "Apple", tier: "Top" },
    { name: "Birch", tier: "Heart" },
    { name: "Patchouli", tier: "Heart" },
    { name: "Rose", tier: "Heart" },
    { name: "Oakmoss", tier: "Base" },
    { name: "Musk", tier: "Base" },
    { name: "Ambergris", tier: "Base" },
    { name: "Vanilla", tier: "Base" },
  ],
  linen: [
    { name: "Neroli", tier: "Top" },
    { name: "Black pepper", tier: "Top" },
    { name: "Iris", tier: "Heart" },
    { name: "Geranium", tier: "Heart" },
    { name: "Maté", tier: "Heart" },
    { name: "Amber", tier: "Base" },
    { name: "Cedar", tier: "Base" },
    { name: "Patchouli", tier: "Base" },
  ],
  mercury: [
    { name: "Grapefruit", tier: "Top" },
    { name: "Luminous fruit accord", tier: "Heart" },
    { name: "Amberwood", tier: "Base" },
    { name: "Musk", tier: "Base" },
  ],
  mystique: [
    { name: "Pistachio", tier: "Top" },
    { name: "Almond", tier: "Top" },
    { name: "Heliotrope", tier: "Heart" },
    { name: "Jasmine", tier: "Heart" },
    { name: "Salted caramel", tier: "Base" },
    { name: "Vanilla", tier: "Base" },
    { name: "Sandalwood", tier: "Base" },
  ],
  "neroli-code": [
    { name: "Neroli", tier: "Top" },
    { name: "Petitgrain", tier: "Top" },
    { name: "Smoky black tea", tier: "Heart" },
    { name: "White musk", tier: "Base" },
  ],
  oasis: [
    { name: "Citron", tier: "Top" },
    { name: "Bergamot", tier: "Top" },
    { name: "Orange", tier: "Top" },
    { name: "Black tea", tier: "Heart" },
    { name: "Ginger", tier: "Heart" },
    { name: "Ambroxan", tier: "Base" },
  ],
  poseidon: [
    { name: "Sea breeze", tier: "Top" },
    { name: "Citrus", tier: "Top" },
    { name: "White florals", tier: "Heart" },
    { name: "Sea salt", tier: "Heart" },
    { name: "Ambergris", tier: "Base" },
    { name: "Light woods", tier: "Base" },
    { name: "Musk", tier: "Base" },
  ],
  "raw-seduction": [
    { name: "Wild apple", tier: "Top" },
    { name: "Bergamot", tier: "Top" },
    { name: "Cardamom", tier: "Heart" },
    { name: "Cypress", tier: "Heart" },
    { name: "Cedar", tier: "Base" },
    { name: "Vetiver", tier: "Base" },
    { name: "Tonka", tier: "Base" },
  ],
  sapphire: [
    { name: "Pear", tier: "Top" },
    { name: "Ginger", tier: "Top" },
    { name: "Mint", tier: "Top" },
    { name: "Orange blossom", tier: "Heart" },
    { name: "Ambroxan", tier: "Base" },
    { name: "White musk", tier: "Base" },
  ],
  "secret-no-7": [
    { name: "Pear", tier: "Top" },
    { name: "Bergamot", tier: "Top" },
    { name: "Vanilla orchid", tier: "Heart" },
    { name: "Vetiver", tier: "Base" },
    { name: "Ambroxan", tier: "Base" },
    { name: "Vanilla", tier: "Base" },
  ],
  "shadow-of-the-sea": [
    { name: "Marine notes", tier: "Top" },
    { name: "Bergamot", tier: "Top" },
    { name: "Rosemary", tier: "Heart" },
    { name: "Clary sage", tier: "Heart" },
    { name: "Geranium", tier: "Heart" },
    { name: "Patchouli", tier: "Base" },
    { name: "Incense", tier: "Base" },
    { name: "Ambery woods", tier: "Base" },
  ],
  "shore-club": [
    { name: "Lemon", tier: "Top" },
    { name: "Orange", tier: "Top" },
    { name: "Blackcurrant", tier: "Top" },
    { name: "Mint", tier: "Heart" },
    { name: "Coriander", tier: "Heart" },
    { name: "Apricot", tier: "Heart" },
    { name: "Ambrette", tier: "Base" },
    { name: "Musk", tier: "Base" },
  ],
  "tonic-club": [
    { name: "Juniper", tier: "Top" },
    { name: "Coriander", tier: "Top" },
    { name: "Nutmeg", tier: "Heart" },
    { name: "Aromatic spices", tier: "Heart" },
    { name: "Musk", tier: "Base" },
    { name: "Ambery woods", tier: "Base" },
    { name: "Vanilla", tier: "Base" },
  ],
  "vanilla-blanche": [
    { name: "Brown sugar", tier: "Top" },
    { name: "Jasmine", tier: "Top" },
    { name: "Vanilla orchid", tier: "Heart" },
    { name: "Tonka", tier: "Heart" },
    { name: "Amber", tier: "Base" },
    { name: "Musk", tier: "Base" },
    { name: "Patchouli", tier: "Base" },
  ],
  "vintage-vanilla": [
    { name: "Vanilla pods", tier: "Top" },
    { name: "Orris", tier: "Heart" },
    { name: "White musk", tier: "Heart" },
    { name: "Sandalwood", tier: "Base" },
    { name: "Tonka", tier: "Base" },
  ],
  wayne: [
    { name: "Bergamot", tier: "Top" },
    { name: "Pineapple", tier: "Top" },
    { name: "Pink pepper", tier: "Top" },
    { name: "Lavender", tier: "Heart" },
    { name: "Cedar", tier: "Heart" },
    { name: "Incense", tier: "Heart" },
    { name: "Ambroxan", tier: "Base" },
    { name: "Patchouli", tier: "Base" },
    { name: "Birch", tier: "Base" },
  ],
};
