import "server-only";
import { createHash, createHmac, timingSafeEqual } from "node:crypto";

/**
 * The sign-in cookie: {uid, sv, iat, exp} plus an HMAC-SHA256 seal. The key
 * is a random secret kept in the private accounts document (made at setup),
 * so no key has to be generated by hand or passed around; replacing it signs
 * everyone out. The role is never in the cookie: it is read from the account
 * on every request, so a role change or removal applies at once, and sv (the
 * account's session version) lets "sign out everywhere" end old cookies.
 *
 * Host-only (__Host-: Secure, Path=/, no Domain), never on COOKIE_DOMAIN,
 * which is shared with Shopify's checkout. SameSite=Lax, so a dashboard link
 * opened from WhatsApp keeps you signed in.
 */
export const SESSION_COOKIE = process.env.NODE_ENV === "production" ? "__Host-eternal_dash" : "eternal_dash";
export const SESSION_DAYS = 7;
export type Session = { uid: string; sv: number; iat: number; exp: number };

const mac = (payload: string, secret: string) => createHmac("sha256", secret).update(payload).digest();

export function seal(s: Session, secret: string) {
  const payload = Buffer.from(JSON.stringify(s)).toString("base64url");
  return `${payload}.${mac(payload, secret).toString("base64url")}`;
}

export function unseal(value: string | undefined, secret: string): Session | null {
  if (!value || value.length > 512 || !secret) return null;
  const [payload, sig] = value.split(".");
  if (!payload || !sig) return null;
  // Hash both sides first so timingSafeEqual always compares equal lengths.
  const given = createHash("sha256").update(Buffer.from(sig, "base64url")).digest();
  const wanted = createHash("sha256").update(mac(payload, secret)).digest();
  if (!timingSafeEqual(given, wanted)) return null;
  try {
    const s = JSON.parse(Buffer.from(payload, "base64url").toString()) as Session;
    return typeof s.uid === "string" && Number.isFinite(s.sv) && Number.isFinite(s.exp) && s.exp > Date.now() / 1000 ? s : null;
  } catch {
    return null;
  }
}

export const cookieOptions = (maxAgeSeconds: number) => ({
  httpOnly: true,
  secure: process.env.NODE_ENV === "production",
  sameSite: "lax" as const,
  path: "/",
  maxAge: maxAgeSeconds,
});
