// Generated by tools/timeline.mjs from storyboard.json — edit the storyboard, not this file.
window.TIMELINE = {
 "title": "eternal: Salt, stone and golden hour",
 "duration": 96.3,
 "scenes": [
  {
   "slug": "first-light",
   "title": "First light",
   "start": 0,
   "duration": 8.2,
   "in": {
    "type": "cut",
    "duration": 0
   },
   "grain": 0.035
  },
  {
   "slug": "already-applied",
   "title": "The direction, applied",
   "start": 7,
   "duration": 8,
   "in": {
    "type": "light-wipe",
    "duration": 1.2
   },
   "grain": 0
  },
  {
   "slug": "four-principles",
   "title": "Four principles",
   "start": 14.4,
   "duration": 20.6,
   "in": {
    "type": "crossfade",
    "duration": 0.6
   },
   "grain": 0
  },
  {
   "slug": "one-story-per-bottle",
   "title": "One story per bottle",
   "start": 33.8,
   "duration": 14.9,
   "in": {
    "type": "light-wipe",
    "duration": 1.2
   },
   "grain": 0.035
  },
  {
   "slug": "three-lines",
   "title": "Three lines, one house",
   "start": 47.5,
   "duration": 9.4,
   "in": {
    "type": "dip-to-linen",
    "duration": 1.2
   },
   "grain": 0
  },
  {
   "slug": "colour",
   "title": "Colour",
   "start": 56.3,
   "duration": 10,
   "in": {
    "type": "crossfade",
    "duration": 0.6
   },
   "grain": 0
  },
  {
   "slug": "typography",
   "title": "Typography",
   "start": 65.7,
   "duration": 6.2,
   "in": {
    "type": "crossfade",
    "duration": 0.6
   },
   "grain": 0
  },
  {
   "slug": "motion",
   "title": "Motion",
   "start": 71.3,
   "duration": 6,
   "in": {
    "type": "crossfade",
    "duration": 0.6
   },
   "grain": 0
  },
  {
   "slug": "storefront-desktop",
   "title": "The storefront",
   "start": 76.7,
   "duration": 7.6,
   "in": {
    "type": "crossfade",
    "duration": 0.6
   },
   "grain": 0
  },
  {
   "slug": "storefront-mobile",
   "title": "Mobile first",
   "start": 83.7,
   "duration": 7.4,
   "in": {
    "type": "crossfade",
    "duration": 0.6
   },
   "grain": 0
  },
  {
   "slug": "never-meant-to-fade",
   "title": "Never meant to fade",
   "start": 89.9,
   "duration": 6.4,
   "in": {
    "type": "light-wipe",
    "duration": 1.2
   },
   "grain": 0.035
  }
 ]
};
