// Writes reel/timeline.js from reel/storyboard.json and checks the arithmetic.
//   node reel/tools/timeline.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const REEL = path.join(here, "..");
const sb = JSON.parse(fs.readFileSync(path.join(REEL, "storyboard.json"), "utf8"));
const problems = [];
const scenes = sb.scenes.map((s, i) => {
  const prev = sb.scenes[i - 1];
  if (prev) {
    const prevEnd = prev.start + prev.duration;
    const overlap = prevEnd - s.start;
    if (overlap < -1e-6) problems.push(`${s.slug} starts ${(-overlap).toFixed(2)}s after ${prev.slug} ends — a gap of black`);
    if (s.transitionIn.type !== "cut" && overlap + 1e-6 < s.transitionIn.duration) problems.push(`${s.slug}: ${s.transitionIn.type} lasts ${s.transitionIn.duration}s but overlaps ${prev.slug} by only ${overlap.toFixed(2)}s`);
  }
  return { slug: s.slug, title: s.title, start: +s.start.toFixed(3), duration: +s.duration.toFixed(3), in: { type: s.transitionIn.type, duration: s.transitionIn.duration }, grain: s.grain ?? 0 };
});
const end = Math.max(...scenes.map((s) => s.start + s.duration));
if (Math.abs(end - sb.totalDuration) > 0.05) problems.push(`scenes end at ${end.toFixed(2)}s but totalDuration is ${sb.totalDuration}s`);
const out = `// Generated by tools/timeline.mjs from storyboard.json — edit the storyboard, not this file.\nwindow.TIMELINE = ${JSON.stringify({ title: sb.title, duration: +end.toFixed(3), scenes }, null, 1)};\n`;
fs.writeFileSync(path.join(REEL, "timeline.js"), out);
console.log(`timeline.js: ${scenes.length} scenes, ${end.toFixed(2)}s`);
for (const s of scenes) console.log(`  ${s.start.toFixed(2).padStart(6)}s +${s.duration.toFixed(2).padStart(5)}s  ${s.in.type.padEnd(12)} ${s.slug}`);
if (problems.length) { console.log("PROBLEMS:\n  " + problems.join("\n  ")); process.exitCode = 1; }
